version: '3'

services: 
    nextjs-ui: 

        build: 
            context: ./
        ports: 
            - "5000:3000"
        container_name: nextjs-ui
        stdin_open: true
        volumes:
           - ./chatty:/usr/src/app/chatty
           - /usr/src/app/chatty/node_modules
